neo4j:
    image: neo4j:3.0.7
    environment:
        NEO4J_AUTH: "none"
    ports:
        - "7474:7474"
        - "7687:7687"
    volumes:
        - ./neo4j-data:/data
        - ./bin:/scripts

app:
    image: chairfield/neo-updating-domains
    environment:
        NEO_ADDRESS: "neo4j"
    ports:
        - "8000:8000"
    links:
        - neo4j

