swagger: "2.0"
info:
  version: "0.0.1"
  title: Domain Graph
# during dev, should point to your local machine
host: localhost:10010
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    x-swagger-router-controller: pets
    get:
      description: List all pets
      operationId: listPets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of pets
          schema:
            $ref: Pets
        default:
          description: Error
          schema:
            $ref: Error
      tags:
        - pets
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Pet:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  Pets:
    properties:
      type: array
      items:
        $ref: Pet
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer,
        format: int32
      message:
        type: string
